export {
  createSupabaseClient,
  getSupabaseConfig,
  supabase,
  SupabaseConfigurationError,
} from "./supabase.js";

export type {
  SupabaseConfig,
  SupabaseEnvironment,
  TypedSupabaseClient,
} from "./supabase.js";

export { DATABASE_CONSTRAINTS } from "./types.js";

export type {
  AcademicRecord,
  CommentsInsert,
  CommentsRow,
  CommentsUpdate,
  CoursesInsert,
  CoursesRow,
  CoursesUpdate,
  Database,
  Json,
  GalleryImagesInsert,
  GalleryImagesRow,
  GalleryImagesUpdate,
  LikertScaleValue,
  MalaysianStudyLocation,
  MonthlyHouseholdIncome,
  ModerationStatus,
  ParentalPreferences,
  PaymentsInsert,
  PaymentsRow,
  PaymentStatus,
  PaymentsUpdate,
  ProfileRole,
  PersonalityTestAnswers,
  ProfilesInsert,
  ProfilesRow,
  ProfilesUpdate,
  PublicTableName,
  RecommendationResultsInsert,
  RecommendationResultsRow,
  RecommendationResultsUpdate,
  ReportAccessGrantKind,
  ReportAccessGrantStatus,
  ReportAccessGrantsInsert,
  ReportAccessGrantsRow,
  ReportAccessGrantsUpdate,
  ReviewLikesInsert,
  ReviewLikesRow,
  ReviewLikesUpdate,
  ReviewsInsert,
  ReviewsRow,
  ReviewsUpdate,
  PublishedReviewsRow,
  PublishedReviewsInsert,
  PublishedReviewsUpdate,
  SessionStudentBindingStatus,
  SessionStudentBindingsInsert,
  SessionStudentBindingsRow,
  SessionStudentBindingsUpdate,
  SessionsInsert,
  SessionsRow,
  SessionStatus,
  SessionsUpdate,
  StudentAssessmentsInsert,
  StudentAssessmentsRow,
  StudentAssessmentsUpdate,
  SpmGrade,
  Tables,
  TablesInsert,
  TablesUpdate,
  Timestamp,
  UniversitiesInsert,
  UniversitiesRow,
  UniversitiesUpdate,
  Uuid,
  VibeCheckQuiz,
} from "./types.js";
