export {
  createSupabaseClient,
  getSupabaseConfig,
  supabase,
  SupabaseConfigurationError,
} from "./supabase.js";

export type {
  SupabaseConfig,
  SupabaseEnvironment,
  TypedSupabaseClient,
} from "./supabase.js";

export { DATABASE_CONSTRAINTS } from "./types.js";

export type {
  CommentsInsert,
  CommentsRow,
  CommentsUpdate,
  CoursesInsert,
  CoursesRow,
  CoursesUpdate,
  Database,
  GalleryImagesInsert,
  GalleryImagesRow,
  GalleryImagesUpdate,
  Json,
  PaymentsInsert,
  PaymentsRow,
  PaymentStatus,
  PaymentsUpdate,
  ProfileRole,
  ProfilesInsert,
  ProfilesRow,
  ProfilesUpdate,
  PublicTableName,
  RecommendationResultsInsert,
  RecommendationResultsRow,
  RecommendationResultsUpdate,
  ReviewLikesInsert,
  ReviewLikesRow,
  ReviewLikesUpdate,
  ReviewsInsert,
  ReviewsRow,
  ReviewsUpdate,
  SessionsInsert,
  SessionsRow,
  SessionStatus,
  SessionsUpdate,
  StudentAssessmentsInsert,
  StudentAssessmentsRow,
  StudentAssessmentsUpdate,
  Tables,
  TablesInsert,
  TablesUpdate,
  Timestamp,
  UniversitiesInsert,
  UniversitiesRow,
  UniversitiesUpdate,
  Uuid,
} from "./types.js";
