import type { Review } from "./types";

export const SEED_REVIEWS: Review[] = [
  {
    id: "seed-aisha",
    course: "Computer Science",
    year: "Year 3",
    rating: 5,
    greenFlags: "Industry-led projects and lecturers who answer after class.",
    redFlags: "Prime parking disappears before the 9am lecture rush.",
    spillTheTea: "The workload gets real in semester two, but the group projects actually mirror how product teams work. I left with a portfolio, not just a transcript.",
    vibeTags: ["Career-ready", "Collaborative", "Fast-paced"],
    isAnonymous: false,
    authorLabel: "Community member · Year 3",
    createdAt: "2026-07-12T09:30:00.000Z",
    likesCount: 84,
    comments: [
      { id: "comment-1", authorLabel: "Community member", text: "The parking detail is painfully accurate." },
    ],
  },
  {
    id: "seed-business",
    course: "International Business",
    year: "Year 2",
    rating: 4,
    greenFlags: "A genuinely international cohort and strong case competitions.",
    redFlags: "Some large lecture sections feel impersonal.",
    spillTheTea: "You get the most value when you join a society early. The people I met there led to two competition trips and my current internship.",
    vibeTags: ["Global", "Social", "Opportunity-rich"],
    isAnonymous: true,
    authorLabel: "Anonymous community member",
    createdAt: "2026-07-09T14:15:00.000Z",
    likesCount: 51,
    comments: [],
  },
  {
    id: "seed-design",
    course: "Mass Communication",
    year: "Year 4",
    rating: 4,
    greenFlags: "Great production facilities and lecturers with newsroom experience.",
    redFlags: "Equipment booking gets competitive around final projects.",
    spillTheTea: "Ask seniors which electives have the best briefs. A good lecturer turns one module into a portfolio piece you can talk about for years.",
    vibeTags: ["Creative", "Hands-on", "Portfolio-first"],
    isAnonymous: true,
    authorLabel: "Anonymous community member",
    createdAt: "2026-07-05T03:20:00.000Z",
    likesCount: 37,
    comments: [],
  },
];
