import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { Checkout } from "./Checkout";
import { Results } from "./Results";

const sessionId = "312dce99-2f20-49fd-8c69-220d624d35be";

vi.mock("../lib/portal-data", () => ({
  authenticateParentAccount: vi.fn(),
  confirmCurrentParentOwnership: vi.fn(),
  grantDemoReportAccess: vi.fn(),
  getAuthorizedReport: vi.fn(),
  getSharedCatalog: vi.fn(),
}));

import { confirmCurrentParentOwnership, getAuthorizedReport, getSharedCatalog, grantDemoReportAccess } from "../lib/portal-data";

function renderRoute(path: string) {
  return render(<MemoryRouter initialEntries={[path]} future={{ v7_relativeSplatPath: true, v7_startTransition: true }}><Routes><Route path="checkout/:id" element={<Checkout />} /><Route path="results/:id" element={<Results />} /><Route path="parent/:id" element={<h1>Parent sign-in</h1>} /></Routes></MemoryRouter>);
}

describe("server-authoritative demo report access", () => {
  beforeEach(() => {
    localStorage.clear();
    vi.clearAllMocks();
    vi.mocked(getSharedCatalog).mockRejectedValue(new Error("Shared university catalogue is unavailable."));
  });

  it("does not unlock results when localStorage claims a successful payment", async () => {
    localStorage.setItem(`inpel:session:${sessionId}`, JSON.stringify({
      id: sessionId, createdAt: new Date().toISOString(), status: "completed", studentProgress: 4,
      authentication: { provider: "password", authenticatedAt: new Date().toISOString() },
      payment: { tier: 3, status: "success", paidAt: new Date().toISOString() },
    }));
    vi.mocked(getAuthorizedReport).mockRejectedValue(new Error("The report is not available for this account."));

    renderRoute(`/results/${sessionId}`);

    expect(await screen.findByRole("heading", { name: /report access is unavailable/i })).toBeInTheDocument();
    expect(screen.queryByText(/universiti teknologi malaysia/i)).not.toBeInTheDocument();
  });

  it("does not show checkout controls to a student or unrelated account", async () => {
    vi.mocked(confirmCurrentParentOwnership).mockRejectedValue(new Error("This parent account does not own this invitation."));

    renderRoute(`/checkout/${sessionId}`);

    expect(await screen.findByRole("heading", { name: /secure your family invitation/i })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /activate free demo report/i })).not.toBeInTheDocument();
  });

  it("activates access only through the server RPC", async () => {
    const user = userEvent.setup();
    vi.mocked(confirmCurrentParentOwnership).mockResolvedValue(undefined);
    vi.mocked(grantDemoReportAccess).mockResolvedValue(undefined);

    renderRoute(`/checkout/${sessionId}`);

    await user.click(await screen.findByRole("button", { name: /activate free demo report/i }));
    expect(grantDemoReportAccess).toHaveBeenCalledWith(sessionId);
  });

  it("renders only the report response returned by the server", async () => {
    vi.mocked(getAuthorizedReport).mockResolvedValue({
      sessionId,
      payload: {
        session_id: sessionId,
        method_disclosure: "Recommendations are generated by the approved server-side matching method.",
        recommendations: [{ university_name: "Server University", match_score: 81, reason: "Returned by the report service." }],
      },
    });

    renderRoute(`/results/${sessionId}`);

    expect(await screen.findByRole("heading", { name: "Server University" })).toBeInTheDocument();
    expect(screen.getByText(/approved server-side matching method/i)).toBeInTheDocument();
    expect(screen.queryByText(/universiti teknologi malaysia/i)).not.toBeInTheDocument();
  });

  it("renders programme records from the shared catalogue without a local fallback", async () => {
    vi.mocked(getAuthorizedReport).mockResolvedValue({ sessionId, payload: { session_id: sessionId } });
    vi.mocked(getSharedCatalog).mockResolvedValue({
      institutions: [{
        referenceInstitutionId: "institution-1",
        institutionName: "Universiti Data Sebenar",
        institutionPreviousName: null,
        universityId: null,
        isLinkedToUniversity: false,
        programmeCount: 1,
      }],
      programmes: [{
        referenceInstitutionId: "institution-1",
        institutionName: "Universiti Data Sebenar",
        canonicalRecordId: "programme-1",
        referenceNo: "MQA/FA0001",
        referenceFamily: "MQA",
        qualificationName: "Diploma Sains Data",
        previousQualificationName: null,
        necCode: "0613",
        necDescription: "Software and applications development and analysis",
        necBroadArea: "Information and Communication Technologies",
        courseId: null,
        isLinkedToCourse: false,
      }],
    });

    renderRoute(`/results/${sessionId}`);

    expect(await screen.findByRole("heading", { name: "Diploma Sains Data" })).toBeInTheDocument();
    expect(screen.getByText("Universiti Data Sebenar")).toBeInTheDocument();
    expect(screen.getByText("MQA/FA0001")).toBeInTheDocument();
  });

  it("shows an unavailable state instead of sample catalogue records", async () => {
    vi.mocked(getAuthorizedReport).mockResolvedValue({ sessionId, payload: { session_id: sessionId } });

    renderRoute(`/results/${sessionId}`);

    expect(await screen.findByRole("heading", { name: /shared catalogue is unavailable/i })).toBeInTheDocument();
    expect(screen.getByText(/no sample university or programme data has been substituted/i)).toBeInTheDocument();
  });
});
